import React, { useState } from "react";
import supabase from "../../lib/supabase";
import { useNavigate } from "react-router-dom";

export default function Index() {
    const [mode, setMode] = useState<"signin" | "signup">("signin");
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  const reset = () => setError(null);

  // 🔧 Helper: upsert user profile
  async function upsertUserProfile(userId: string, userEmail: string, usernameValue: string) {
    const { error } = await supabase.from("user_profile").upsert(
      {
        auth_user: userId,        // UUID from Supabase Auth
        email: userEmail,
        username: usernameValue,
        updated_at: new Date().toISOString(),
        // id is bigint primary key, auto-generated by DB
        // created_at handled by DB default
      },
      { onConflict: "auth_user" }
    );

    if (error) {
      console.error("Upsert error:", error);
      throw error;
    }
  }

  async function handleAuth() {
    reset();
    if (!email || !password) {
      setError("Please provide both email and password.");
      return;
    }

    setLoading(true);
    try {
      if (mode === "signup") {
        const { data, error } = await supabase.auth.signUp({
          email,
          password,
          options: { data: { username } },
        });

        if (error) {
          setError(error.message || String(error));
        } else {
          const userId = data?.user?.id;
          if (userId) {
            await upsertUserProfile(userId, email, username);
            navigate(`/`);
          }
        }
      } else {
        const { data, error } = await supabase.auth.signInWithPassword({
          email,
          password,
        });

        if (error) {
          setError(error.message || String(error));
        } else {
          let userId = data?.user?.id;
          if (!userId) {
            const res = await supabase.auth.getUser();
            userId = res?.data?.user?.id;
          }

          if (userId) {
            const { data: userInfo } = await supabase.auth.getUser();
            const userEmail = userInfo?.user?.email ?? email;
            const usernameFromMeta = userInfo?.user?.user_metadata?.username || username;

            await upsertUserProfile(userId, userEmail, usernameFromMeta);
            navigate(`/`);
          } else {
            setError("Signed in but could not determine user id.");
          }
        }
      }
    } catch (e: any) {
      setError(e?.message ?? String(e));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-linear-to-br from-sky-50 to-white">
      <div className="max-w-4xl w-full mx-4 grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
        <div className="hidden md:flex flex-col justify-center p-8 bg-white rounded-lg shadow-lg">
          <h1 className="text-3xl font-extrabold text-sky-700 mb-4">
            Welcome to G‑mail Clone
          </h1>
          <p className="text-gray-600">
            Fast, minimal, and built for learning. Sign in to access your
            mailbox and manage emails.
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-lg">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold text-gray-800">
              {mode === "signin" ? "Sign In" : "Create an account"}
            </h2>
            <div className="text-sm text-gray-500">
              {mode === "signin" ? (
                <span>
                  New here?{" "}
                  <button
                    className="text-sky-600 hover:underline"
                    onClick={() => setMode("signup")}
                  >
                    Create account
                  </button>
                </span>
              ) : (
                <span>
                  Already have an account?{" "}
                  <button
                    className="text-sky-600 hover:underline"
                    onClick={() => setMode("signin")}
                  >
                    Sign in
                  </button>
                </span>
              )}
            </div>
          </div>

          {error && <div className="mb-4 text-sm text-red-600">{error}</div>}

          <label className="block mb-2 text-sm text-gray-600">Email</label>
          <input
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            className="w-full mb-4 p-3 border text-black rounded focus:outline-none focus:ring-2 focus:ring-sky-200"
            placeholder="you@example.com"
          />

          {mode === "signup" && (
            <>
              <label className="block mb-2 text-sm text-gray-600">
                Username
              </label>
              <input
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                type="text"
                className="w-full mb-4 p-3 border rounded focus:outline-none focus:ring-2 focus:ring-sky-200"
                placeholder="Display name"
              />
            </>
          )}

          <label className="block mb-2 text-sm text-gray-600">Password</label>
          <input
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            className="w-full mb-4 p-3 border rounded focus:outline-none focus:ring-2 focus:ring-sky-200"
            placeholder="Enter a strong password"
          />

          <button
            type="button"
            onClick={handleAuth}
            disabled={loading}
            className="w-full flex items-center justify-center gap-2 bg-sky-600 hover:bg-sky-700 text-white py-3 rounded font-medium disabled:opacity-60"
          >
            {loading
              ? "Please wait..."
              : mode === "signin"
                ? "Sign In"
                : "Create Account"}
          </button>
        </div>
      </div>
    </div>
  );
}
